Rename command-line options for VC randomization
boogie-org/boogie pull request #678
Opened 2023-01-12 02:11 UTC by shazqadeer

2023-01-12 19:31 UTC, atomb requested changes
Overall, I think this is a great improvement. Given that there's some code out there that depends on the old option name, I'm wondering whether it would be reasonable to still accept it.

2023-01-12 22:50 UTC, shazqadeer commented on Source/ExecutionEngine/CommandLineOptions.cs
> -        case "randomSeedIterations":
I assume you are talking about the Dafny dependency on Boogie.  What process do you suggest we follow for deprecating Boogie features that are no longer necessary or covered by other features? Specifically, when would it be reasonable to drop ```-randomSeedIterations" entirely.

2023-01-13 14:08 UTC, keyboardDrummer commented on Source/ExecutionEngine/CommandLineOptions.cs
> -        case "randomSeedIterations":
Dafny doesn't use the Boogie CLI, so there's no Dafny dependency on this CLI option name.

2023-01-13 19:03 UTC, atomb commented on Source/ExecutionEngine/CommandLineOptions.cs
> -        case "randomSeedIterations":
For anyone using the new top-level commands, that's true. But for anyone using the older options, they're passed through to Boogie directly from the command line. Even though Dafny is using Boogie as a library, it still uses Boogie's option parser for that case.

I'm not sure I have a concrete answer yet as to when it'd be inconsequential to drop it, but I'd like to at least update the Dafny documentation before Boogie changes.

We're overall moving away from the model of automatically passing Boogie options through verbatim, so this isn't likely to be as much of an issue in the future.

2023-01-13 19:34 UTC, shazqadeer commented on Source/ExecutionEngine/CommandLineOptions.cs
> -        case "randomSeedIterations":
I added a case for the old option name. I would like to request you to update Dafny documentation soon and then circle back with a Boogie PR to remove the old option name. Thanks for your feedback and for the great work you did in adding this feature to Boogie.

2023-01-13 20:03 UTC, atomb approved these changes

2023-01-13 20:17 UTC, merged