Set timeout to see where deadlocks are coming from
boogie-org/boogie pull request #932
Opened 2024-08-08 13:08 UTC by keyboardDrummer

2024-08-09 22:35 UTC, atomb requested changes
This looks like a nice improvement. I saw two tiny things in the tests that might be worth a second look.

2024-08-09 22:35 UTC, atomb commented on Test/prover/cvc5-offline.smt2
Did you mean to check in this file?

2024-08-09 22:35 UTC, atomb commented on Test/test2/Rlimitouts0.bpl
> +// RUN: %boogie -processTimeLimit:0 -timeLimit:0 -rlimit:800000 -proverLog:"%t.smt2" "%s"
It might be worth having a process time limit here, too, since there's no strict guarantee that Z3 will ever terminate given a resource limit.

2024-08-12 19:09 UTC, shazqadeer commented
@keyboardDrummer : Thanks for digging into the flaky CI issues. I had also noticed these small tests failing in CI with a timeout and had no idea what was going on.

> Fix a bug that could cause a concurrency related exception in QuantifierInstantiationInfo, which was introduced by https://github.com/boogie-org/boogie/pull/862.

To improve my understanding, could you say a bit more about the bug introduced by my aforementioned PR?

2024-08-13 07:37 UTC, keyboardDrummer commented
> To improve my understanding, could you say a bit more about the bug introduced by my aforementioned PR?

The fix is in this commit: https://github.com/boogie-org/boogie/pull/932/commits/c79011bbe26af6ebf7055ef44d0b96901b4f13e3
While running tests, I saw a concurrent modification exception during a call to HashSet.Add done from `FindInstantiationHints`. Looking at the git history, `FindInstantiationHints` was originally designed to be able to be called concurrently, but since the introduction of the HashSet it no longer supported this. I replaced the use of HashSet with a ConcurrentBag so it can handle concurrent Add calls.

2024-08-13 15:55 UTC, atomb approved these changes

2024-08-13 16:06 UTC, merged